import os
import uuid
import pytz

from django.db import models
from PIL import Image as PILImage
from PIL import ImageOps
from shortuuid.django_fields import ShortUUIDField


# Legacy helper functions kept for backward compatibility with migrations
def contribution_image_upload_to(instance, filename):
    """Legacy upload path - kept for old migrations."""
    _, extension = os.path.splitext(filename)
    filename_root = uuid.uuid4().hex
    return os.path.join("contributions", f"{filename_root}{extension.lower()}")


def set_preview(obj, filename):
    """
    Used as `poster` image for `<model-viewer>`.
    NOTE: Preview will not being resized / compressed since it should be either manually / auto-staged.
    FIXME: LATE_EXP: Auto-stage the Preview when a reconstruction is available.
    """
    upload_to = f"models/{obj.ID}"
    filename = f"{obj.ID}_prev.png"
    return os.path.join(upload_to, filename)


def set_thumbnail(obj, filename):
    """
    Used for the list in the nav.
    """
    upload_to = f"models/{obj.ID}"
    filename = f"{obj.ID}_thumb.png"
    return os.path.join(upload_to, filename)


class Mesh(models.Model):
    """
    Represents a 3D mesh model.
    Maps to old Tirtha's Mesh model exactly.
    """
    # Short for ease of use - primary key
    ID = ShortUUIDField(
        primary_key=True, length=16, max_length=16, verbose_name="Mesh ID"
    )

    # Metadata
    name = models.CharField(max_length=200, blank=False)
    description = models.TextField(
        blank=True, verbose_name="Description", default="Placeholder Text"
    )

    country = models.CharField(max_length=200, blank=False, default="India")
    state = models.CharField(max_length=200, blank=False, default="Odisha")
    district = models.CharField(max_length=200, blank=False, default="Khordha")

    preview = models.ImageField(
        upload_to=set_preview, blank=False, verbose_name="Mesh Preview"
    )
    thumbnail = models.ImageField(
        upload_to=set_thumbnail, blank=False, verbose_name="Mesh Thumbnail"
    )

    # Auto-generated - Used for most tasks
    verbose_id = models.CharField(
        max_length=200,
        blank=True,
        unique=True,
        editable=False,
        default="<auto-generated using country, state & district>",
        verbose_name="Verbose ID",
    )
    # Multiple choices for status: [Pending, Processing, Live, Error]
    status_options = [
        ("Pending", "Pending"),
        ("Processing", "Processing"),
        ("Live", "Live"),
        ("Error", "Error"),
    ]
    status = models.CharField(
        max_length=50, blank=False, choices=status_options, default="Pending"
    )

    # Whether the mesh is accepting images any more
    completed = models.BooleanField(default=False, verbose_name="Completed")
    # Whether to hide the model from the frontend
    hidden = models.BooleanField(default=False, verbose_name="Hidden")

    ## Reconstruction settings
    # NOTE: center_image is admin-only.
    # If need be, an admin can set the filename (no ext)
    # of an image in the .../images/ folder.
    # This feeds into sfmTransform(center_image) to orient the mesh with.
    center_image = models.CharField(
        max_length=200, blank=True, verbose_name="Center Image"
    )
    # Rotation and minimum observation angle for `sfmRotate`, `meshing` & <model-viewer>
    rotaX = models.IntegerField(default=0, verbose_name="Rotation about X-axis")
    rotaY = models.IntegerField(default=0, verbose_name="Rotation about Y-axis")
    rotaZ = models.IntegerField(default=0, verbose_name="Rotation about Z-axis")
    # NOTE: Controls whether to use sfmRotate or orient using <model-viewer>
    # Ideally, we do not want to sfmRotate for each new run.
    orientMesh = models.BooleanField(default=False, verbose_name="Orient Mesh")
    minObsAng = models.IntegerField(
        default=30, verbose_name="Minimum Observation Angle"
    )
    denoise = models.BooleanField(default=False, verbose_name="Denoise")

    # Set automatically
    created_at = models.DateTimeField("Created at", auto_now_add=True)
    updated_at = models.DateTimeField("Updated at", auto_now=True)
    reconstructed_at = models.DateTimeField(
        "Last reconstructed at", blank=True, null=True
    )

    class Meta:
        ordering = ["-updated_at"]
        verbose_name_plural = "Meshes"
        db_table = "sites_mesh"

    def __str__(self):
        return self.verbose_id

    def __repr__(self):
        return f"""
                Mesh(
                    {self.ID},
                    {self.name},
                    {self.description},
                    {self.created_at},
                    {self.updated_at},
                    {self.reconstructed_at},
                    {self.status},
                    {self.completed},
                    {self.hidden}
                )
                """

    def save(self, *args, **kwargs):
        self.verbose_id = (
            self.country + "__" + self.state + "__" + self.district + "__" + self.name
        ).replace(" ", "_")
        super().save(*args, **kwargs)

        # Resizes & compresses thumbnail image
        if self.thumbnail:
            try:
                # Load the uploaded image
                image = PILImage.open(self.thumbnail.path)
                image = ImageOps.exif_transpose(image)
                aspect_ratio = image.width / image.height
                new_width = image.width
                new_height = image.height
                min_dimension = 400

                if image.width >= min_dimension and image.height >= min_dimension:
                    # Preserve aspect ratio
                    if aspect_ratio > 1:  # Landscape
                        new_width = max(min_dimension, int(min_dimension * aspect_ratio))
                        new_height = min_dimension
                    else:  # Portrait
                        new_width = min_dimension
                        new_height = max(min_dimension, int(min_dimension / aspect_ratio))

                # Resize
                resized_image = image.resize((new_width, new_height))

                # Save the resized image at 60% quality
                resized_image.save(self.thumbnail.path, quality=60)
                resized_image.close()

                super().save(*args, **kwargs)
            except Exception:
                pass


class Contributor(models.Model):
    """
    Represents a contributor who uploads images.
    Maps to old Tirtha's Contributor model exactly.
    """
    ID = models.UUIDField(
        primary_key=True, default=uuid.uuid4, editable=False, verbose_name="Contributor ID"
    )

    # Populated via Google SSO / admin panel
    name = models.CharField(max_length=200)
    email = models.EmailField(unique=True)

    active = models.BooleanField(default=True, verbose_name="Active?")

    # Set automatically
    created_at = models.DateTimeField("Created at", auto_now_add=True)
    updated_at = models.DateTimeField("Updated at", auto_now=True)

    # Implements email level banning
    banned = models.BooleanField(default=False, verbose_name="Banned?")
    ban_reason = models.TextField(blank=True, verbose_name="Ban Reason")

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Contributors"
        db_table = "sites_contributor"

    def __str__(self):
        return self.email

    def __repr__(self):
        return f"""
                Contributor(
                    {self.ID},
                    {self.name},
                    {self.email},
                    {self.created_at},
                    {self.updated_at},
                    {self.banned},
                    {self.ban_reason}
                )
                """


class Contribution(models.Model):
    """
    Represents a batch of images contributed by a contributor to a mesh.
    Maps to old Tirtha's Contribution model exactly.
    """
    ID = models.UUIDField(
        primary_key=True, default=uuid.uuid4, verbose_name="Contribution ID"
    )
    mesh = models.ForeignKey(
        Mesh,
        on_delete=models.CASCADE,
        verbose_name="Mesh ID",
        related_name="contributions",
    )
    contributor = models.ForeignKey(
        Contributor,
        on_delete=models.CASCADE,
        verbose_name="Contributor ID",
        related_name="contributions",
    )
    contributed_at = models.DateTimeField(
        auto_now_add=True, verbose_name="Contribution Timestamp"
    )
    processed = models.BooleanField(default=False, verbose_name="Processed by ImageOps")
    processed_at = models.DateTimeField(
        blank=True, null=True, verbose_name="Processed Timestamp"
    )

    class Meta:
        ordering = ["-contributed_at"]
        verbose_name_plural = "Contributions"
        db_table = "sites_contribution"

    def __str__(self):
        return f"{self.ID}"

    def __repr__(self):
        return f"""
                Contribution(
                    {self.ID},
                    {self.mesh},
                    {self.contributor},
                    {self.contributed_at},
                    {self.processed},
                    {self.processed_at}
                )
                """


def set_image(obj, filename):
    """Upload path for images - uses contribution's mesh ID."""
    upload_to = f"models/{obj.contribution.mesh.ID}/images"
    filename = f"{str(obj.ID)}.{filename.split('.')[-1].lower()}"
    return os.path.join(upload_to, filename)


class Image(models.Model):
    """
    Represents an image uploaded as part of a contribution to a mesh.
    Maps to old Tirtha's Image model exactly.
    """
    ID = models.UUIDField(primary_key=True, default=uuid.uuid4, verbose_name="Image ID")
    contribution = models.ForeignKey(
        Contribution, on_delete=models.CASCADE, related_name="images"
    )
    image = models.ImageField(upload_to=set_image, blank=False, max_length=255)
    created_at = models.DateTimeField("Created at", auto_now_add=True)

    # Multiple choices for label - Also incorporates general image quality.
    label_options = [("nsfw", "NSFW"), ("good", "Good"), ("bad", "Bad")]
    label = models.CharField(max_length=50, blank=True, choices=label_options)
    remark = models.TextField(blank=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name_plural = "Images"
        db_table = "sites_image"

    def __str__(self):
        return f"{self.ID}"

    def __repr__(self):
        return f"""
                Image(
                    {self.ID},
                    {self.contribution},
                    {self.image},
                    {self.created_at},
                    {self.label},
                    {self.remark}
                )
                """


class SiteSubmissionRequest(models.Model):
    """
    Separate model for site submission requests.
    Kept separate from Mesh model (this was not in old Tirtha).
    """
    class Status(models.TextChoices):
        PENDING = "pending", "Pending"
        APPROVED = "approved", "Approved"
        REJECTED = "rejected", "Rejected"

    request_id = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    site_name = models.CharField(max_length=255)
    state = models.CharField(max_length=128)
    country = models.CharField(max_length=128)
    description = models.TextField(null=True, blank=True)
    google_maps_url = models.URLField(max_length=500, null=True, blank=True)
    image = models.ImageField(
        upload_to="site_requests/",
        max_length=500,
        null=True,
        blank=True
    )
    latitude = models.FloatField()
    longitude = models.FloatField()
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.PENDING)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at", "-id"]
        db_table = "sites_sitesubmissionrequest"

    def __str__(self):
        return f"{self.site_name} ({self.request_id})"


# Backward-compatible aliases for views.py and other code using the old names
Site = Mesh
ContributionBatch = Contribution
ContributionImage = Image
