# Generated by Django 6.0.4 on 2026-06-13 12:37

import django.db.models.deletion
import shortuuid.django_fields
import sites.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Contributor ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('active', models.BooleanField(default=True, verbose_name='Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('banned', models.BooleanField(default=False, verbose_name='Banned?')),
                ('ban_reason', models.TextField(blank=True, verbose_name='Ban Reason')),
            ],
            options={
                'verbose_name_plural': 'Contributors',
                'db_table': 'sites_contributor',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('ID', shortuuid.django_fields.ShortUUIDField(alphabet=None, length=16, max_length=16, prefix='', primary_key=True, serialize=False, verbose_name='Mesh ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='Placeholder Text', verbose_name='Description')),
                ('country', models.CharField(default='India', max_length=200)),
                ('state', models.CharField(default='Odisha', max_length=200)),
                ('district', models.CharField(default='Khordha', max_length=200)),
                ('preview', models.ImageField(upload_to=sites.models.set_preview, verbose_name='Mesh Preview')),
                ('thumbnail', models.ImageField(upload_to=sites.models.set_thumbnail, verbose_name='Mesh Thumbnail')),
                ('verbose_id', models.CharField(blank=True, default='<auto-generated using country, state & district>', editable=False, max_length=200, unique=True, verbose_name='Verbose ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Live', 'Live'), ('Error', 'Error')], default='Pending', max_length=50)),
                ('completed', models.BooleanField(default=False, verbose_name='Completed')),
                ('hidden', models.BooleanField(default=False, verbose_name='Hidden')),
                ('center_image', models.CharField(blank=True, max_length=200, verbose_name='Center Image')),
                ('rotaX', models.IntegerField(default=0, verbose_name='Rotation about X-axis')),
                ('rotaY', models.IntegerField(default=0, verbose_name='Rotation about Y-axis')),
                ('rotaZ', models.IntegerField(default=0, verbose_name='Rotation about Z-axis')),
                ('orientMesh', models.BooleanField(default=False, verbose_name='Orient Mesh')),
                ('minObsAng', models.IntegerField(default=30, verbose_name='Minimum Observation Angle')),
                ('denoise', models.BooleanField(default=False, verbose_name='Denoise')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('reconstructed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last reconstructed at')),
            ],
            options={
                'verbose_name_plural': 'Meshes',
                'db_table': 'sites_mesh',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSubmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('site_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, null=True)),
                ('google_maps_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to='site_requests/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sites_sitesubmissionrequest',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Contribution ID')),
                ('contributed_at', models.DateTimeField(auto_now_add=True, verbose_name='Contribution Timestamp')),
                ('processed', models.BooleanField(default=False, verbose_name='Processed by ImageOps')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='Processed Timestamp')),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='sites.contributor', verbose_name='Contributor ID')),
                ('mesh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='sites.mesh', verbose_name='Mesh ID')),
            ],
            options={
                'verbose_name_plural': 'Contributions',
                'db_table': 'sites_contribution',
                'ordering': ['-contributed_at'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('ID', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Image ID')),
                ('image', models.ImageField(max_length=255, upload_to=sites.models.set_image)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('label', models.CharField(blank=True, choices=[('nsfw', 'NSFW'), ('good', 'Good'), ('bad', 'Bad')], max_length=50)),
                ('remark', models.TextField(blank=True)),
                ('contribution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sites.contribution')),
            ],
            options={
                'verbose_name_plural': 'Images',
                'db_table': 'sites_image',
                'ordering': ['-created_at'],
            },
        ),
    ]
