# Generated by Django 6.0.4 on 2026-05-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
