# Generated by Django 6.0.4 on 2026-05-09 10:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_site_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
