# Generated by Django 6.0.4 on 2026-05-14 06:28

import django.core.validators
import django.db.models.deletion
import sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_images', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_batches', to='sites.contributor')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_batches', to='sites.site')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ContributionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=sites.models.contribution_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tif', 'tiff'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sites.contributionbatch')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_images', to='sites.site')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
