# Generated by Django 6.0.4 on 2026-05-14 11:00

import django.core.validators
import sites.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_add_ids_and_totals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionbatch',
            name='batch_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contributionimage',
            name='image',
            field=models.ImageField(upload_to=sites.models.contribution_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tif', 'tiff'])]),
        ),
        migrations.AlterField(
            model_name='contributionimage',
            name='image_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='contributor',
            name='contributor_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='site_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
