# Generated by Django 6.0.4 on 2026-05-14 11:34

import django.core.validators
import sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_contributionbatch_batch_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributionimage',
            name='image',
            field=models.ImageField(max_length=500, upload_to=sites.models.contribution_image_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp', 'gif', 'bmp', 'tif', 'tiff'])]),
        ),
    ]
