# Generated by Django 6.0.4 on 2026-05-16 11:01

import sites.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_alter_contributionimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSubmissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('site_name', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('google_maps_url', models.URLField(max_length=500)),
                ('source_url', models.URLField(max_length=500)),
                ('image', models.ImageField(max_length=500, upload_to=sites.models.site_submission_request_upload_to)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
