# Generated by Django 6.0.4 on 2026-05-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0009_sitesubmissionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesubmissionrequest',
            name='source_url',
        ),
        migrations.AddField(
            model_name='sitesubmissionrequest',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
