# Generated by Django 6.0.4 on 2026-05-19 10:47

import sites.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0010_remove_sitesubmissionrequest_source_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesubmissionrequest',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='sitesubmissionrequest',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=sites.models.site_submission_request_upload_to),
        ),
    ]
