# Generated by Django 6.0.6 on 2026-06-17 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_alter_sitesubmissionrequest_google_maps_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionimage',
            name='camera_make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributionimage',
            name='camera_model',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributionimage',
            name='date_taken',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contributionimage',
            name='focal_length',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contributionimage',
            name='gps_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contributionimage',
            name='gps_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
