# Generated by Django 6.0.6 on 2026-06-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0012_contributionimage_camera_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributionimage',
            name='is_compressed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contributionimage',
            name='original_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contributionimage',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contributionimage',
            name='uploaded_file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
